Transposing a matrix

In [ ]:
import numpy as np

m = np.random.randn(2, 5)

tm = m.T

print("Matrix A")
print(m)
print("Transposed of Matrix A")
print(tm)

Generating Special Matrices

In [ ]:
import numpy as np

I = np.eye(4)
print("Identical Matrix")
print(I)
O = np.ones((3, 5))
print("Ones Matrix")
print(O)
Z = np.zeros((4, 3))
print(Z)

Diagonal Matrix

In [ ]:
import numpy as np

d = np.diag([3, 4, 2, 4])
print(d)

In [ ]:
import numpy as np

dn = np.random.randn(4)
d = np.diag(dn)
print(d)

Augmented Matrix

In [ ]:
import numpy as np

m1 = np.random.randn(4, 3)
m2 = np.random.randn(4, 3)

print("First Matrix")
print(m1)
print("Second Matrix")
print(m2)
print("Concatenation of First and Second matrices")

# axis = 1 will put matrices side by side where axis = 0 will put them on top of each other
c = np.concatenate((m1, m2), axis = 1)
print(c)

Extracting traingular matrices

In [1]:
import numpy as np

m = np.random.randn(4, 3)

print("Matrix A")
print(m)

print("Up triangle matrix of Matrix A")
u = np.triu(m)
print(u)
print("Down triangle matrix of Matrix A")
d = np.tril(m)
print(d)

Matrix A
[[-0.82160996  1.49546289  1.37022913]
 [ 1.42783936 -0.88025296 -0.33955464]
 [-1.30773136 -1.06590109  0.31828089]
 [ 1.11189566  0.329891    0.55542026]]
Up triangle matrix of Matrix A
[[-0.82160996  1.49546289  1.37022913]
 [ 0.         -0.88025296 -0.33955464]
 [ 0.          0.          0.31828089]
 [ 0.          0.          0.        ]]
Down triangle matrix of Matrix A
[[-0.82160996  0.          0.        ]
 [ 1.42783936 -0.88025296  0.        ]
 [-1.30773136 -1.06590109  0.31828089]
 [ 1.11189566  0.329891    0.55542026]]


Hankel and Toeplitz Matrices

In [1]:
from scipy.linalg import hankel, toeplitz

t = [1, 2, 3, 4]

print("Toeplitz of Matrix t")
T = toeplitz(t)
print(T)

print("Hankel of Matrix t")
H = hankel(t, r = [2, 3, 4, 1])
print(H)

Toeplitz of Matrix t
[[1 2 3 4]
 [2 1 2 3]
 [3 2 1 2]
 [4 3 2 1]]
Hankel of Matrix t
[[1 2 3 4]
 [2 3 4 3]
 [3 4 3 4]
 [4 3 4 1]]


Shifting matrix

In [ ]:
import numpy as np

l = 21

I = np.eye(4)
print("Identity Matrix")
print(I)
A = np.random.randn(4, 4)
print("Matrix A")
print(A)
As = A + l*I
print("Shifted Matrix")
print(As)

Trace in a matrix

In [1]:
import numpy as np

m = np.random.randn(4,4)
print("Matrix m")
print(m)
t = np.trace(m)
print("Trace of matrix m")
print(t)

Matrix m
[[-0.9204417   0.94960836 -0.94478182 -1.15056634]
 [-0.88109818 -0.30969265  0.47628616  0.15666665]
 [-0.88165545 -2.56428087 -1.89886967  0.92359117]
 [-0.30448044 -1.02505092  0.99805466  0.49621782]]
Trace of matrix m
-2.632786206973717
